### ISSUE TITLE
Đồng bộ giữ Windows calendar và google calendar gặp trục trặc

### ISSUE THREAD

**Issue by huuson889** [bkalendar/bkalendar.github.io#4]
Hi bạn,
App bạn làm rất hữu ích nhưng khi dùng mình phát hiện lỗi sau
1. Nếu bạn tạo 1 lịch (vd: HK212) sau đó import lịch tải về vào trên GG calendar thì sẽ tạo mỗi môn một dãy các events liên kết nhau (mình có 9 môn), việc này rất tiện trong việc edit mỗi môn học (vd: mình thêm link events đầu tiên, có thể cập nhật các events sau đó với một môn). Nhưng VẤN ĐỀ là khi đồng bộ Windows calendar thì nó chỉ hiện 9 events đầu tiên, các events connected tiếp nó không hiển thị.
2. Ngược lại, nếu import lịch tải về vào Windows calender trước thì trên GG calendar sẽ không kết nối các events trong cùng 1 môn với nhau, nên sửa 1 môn event đầu thì các events tiếp theo nó ko chỉnh theo.

Bạn xem có cách nào giải quyết được ko, mình dùng học kỳ thứ 2 rồi và thử đi thử lại rất nhiều mới phát hiện ra lỗi đó.
Thanks bạn nhiều!

**Comment by iceghost** [comment]
Cảm ơn bạn đã báo cho mình.

Hiện tại mình cũng gặp trục trặc với việc đồng bộ lịch trên máy. Vì một lý do nào đó mà ứng dụng Calendar không đọc được các luật recurrence của lịch.

Giải pháp hiện tại mình định làm là giới hạn sử dụng ở Google Calendar, thông qua việc kết nối tài khoản Google. Hy vọng là sẽ giúp khắc phục được chuyện này 😄

**Comment by iceghost** [comment]
@huuson889 Mình vừa làm lại mọi thứ liên quan đến nhập xuất. Hiện tại thời khóa biểu sẽ được xuất thẳng sang Google Calendar, sau đó bạn có thể liên kết ứng dụng Calendar với tài khoản Google nha. Do mọi thứ đã hoạt động ổn bên phía mình nên mình xin phép đóng issue. Nếu vẫn còn vấn đề thì bạn có thể reopen hoặc mở cái khác nha. Cảm ơn bạn.
